### ISSUE TITLE
More photos of the project?

### ISSUE THREAD

**Issue by corrspt** [isinek/led_stairs#1]
Hey!

This isn't an issue. But it's the forum I have to send a message, sorry :)  

Would you be willing to provide more photos (daylight photos, close ups of how cables are hidden, where's the power source/controller). It looks really really great as a finished project. I would like to see the tricks, so that I can learn for a similar project I have in my mind :) 

Thanks!

**Comment by isinek** [comment]
Hi,

No problems, I'll update README.md file and add some pictures from building phase. :)

**Comment by corrspt** [comment]
Thank you very much :) I'll close the issue :) Thanks for sharing your project!
